apiVersion: v1
kind: Pod
metadata:
  name: frontend-3
spec:
  containers:
  - name: app
    image: httpd
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "10"
