apiVersion: v1
kind: Pod
metadata:
  name: frontend-gurantee-resources
spec:
  containers:
  - name: app
    image: httpd
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "50m"
