apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels: 
     app: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat
    ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
     app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
     - containerPort: 80
