apiVersion: v1
kind: Service
metadata:
  name: samplesvc
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 3000  
 #   nodePort: 30001 #expose , if dont give takes default
    protocol: TCP
  selector:
    tier: frontend
